---
- name: Install and configure wordpress on Ubuntu 

  # Use the IP address(es) supplied in the inventory.ini 
  hosts: myhosts
  become: true

  tasks:

      # TASK 8
      #   Wait for a connection to be established to the host
      - name: Wait for connection
        ansible.builtin.wait_for_connection:


      # TASK 9
      #   After connecting, begin installation of necessary drivers and services.
      - name: Install httpd, php, php-mysqli, and mariadb-server
        ansible.builtin.package:
          name:
            - apache2
            - php
            - php-mysql
            - mariadb-server
          state: absent

