---
- name: Install and configure Cockpit. 

  # Use the IP address(es) supplied in the inventory.ini 
  hosts: myhosts
  become: true

  vars:
      user: "NTC"
      _password_: "{{ user | ansible.builtin.password_hash }}"

  tasks:
  
      # TASK 1   
     - name: print user

      # TASK 2
     - name: Install redhat cockpit

      # TASK 3
     - name: Start redhat cockpit

      # TASK 4 - NOTE WCA SOMETIMES GETS THIS WRONG.     
     - name: create user from credentials

       # TASK 5 
     - name: Check if Cockpit is running 

      # TASK 6 - Show the status
     - name: print cockpit status