---
- name: Install and configure Cockpit. 

  # Use the IP address(es) supplied in the inventory.ini 
  hosts: myhosts
  become: true

  vars:
      user: "NTC"
      password: "NTC"

  tasks:
  
      # TASK 1   
     - name: print user

      # TASK 2
     - name: Install redhat cockpit

      # TASK 3
     - name: Start redhat cockpit

      # TASK 4 - NOTE WCA GETS THIS WRONG.  You need to hash the password with the code below:
     #  ansible.builtin.user:
     #    name: "{{ user }}"
     #    password: "{{ password | password_hash('sha512') }}"
     #    shell: /bin/bash
     #    groups: wheel
     #    append: true      
     - name: create user from credentials

     
       # TASK 5 - Check its up
     - name: Check if Cockpit is running 
       ansible.builtin.command: systemctl status cockpit
       register: cockpit_status
       changed_when: false
       failed_when: false

      # TASK 6 - Show the status
     - name: print cockpit status




