---
- name: Install and configure Cockpit on Ubuntu 

  # Use the IP address(es) supplied in the inventory.ini 
  hosts: myhosts
  become: true

  tasks:
  
     # TASK 0
     - name: 

     
     # TASK 1
     - name: 



      # TASK 2   
     - name: 











      # TASK 3
     - name: Install redhat cockpit
  



      # TASK 4
     - name: Start redhat cockpit
    



      # TASK 5 - NOTE WCA GETS THIS WRONG.  You need to hash the password with the  line below:
      # password: "{{ user_password.user_input | password_hash('sha512') }}"
     - name: create user from credentials




      # TASK 6 - Check its up
     - name: Check if Cockpit is running 



      # TASK 7 - Show the URL. 
     - name:  display Cockpit url 





