---
- name: Install and configure Cockpit. 

  # Use the IP address(es) supplied in the inventory.ini 
  hosts: myhosts
  become: true

  tasks:
  
     # TASK 1
     # prompt for user &  prompt for password 

      # TASK 2   
     - name: print credentials

      # TASK 3
     - name: Install redhat cockpit

      # TASK 4
     - name: Start redhat cockpit

      # TASK 5 - NOTE WCA GETS THIS WRONG.  You need to hash the password with the  line below:
      # "password: "{{ user_password.user_input | password_hash('sha512') }}"
     - name: create user from credentials
     
       # TASK 6 - Check its up
     - name: Check if Cockpit is running 

      # TASK 7 - Show the URL.  NOTE WCA sometimes gets this wrong.  You need the two commands below to show the URL:
      # ansible.builtin.debug:
      #  msg: 'Cockpit url: https://{{ inventory_hostname }}:9090'
     - name: print redhat cockpit url  


